# Generated by Django 5.1.6 on 2025-03-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todoo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
